Repository hanaro4-dIA/dia_be, pull requests merged in 2024-12, with the labels that each got.

#39 [feat] : CustomerController의 기능, swagger 및 테스트 추가
  src/main/java/com/dia/dia_be/controller/pb/CustomerController.java
  src/main/java/com/dia/dia_be/domain/Customer.java
  src/main/java/com/dia/dia_be/dto/pb/CustomerDTO.java
  src/main/java/com/dia/dia_be/repository/CustomerRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/CustomerServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/CustomerService.java
  src/test/java/com/dia/dia_be/pb/CustomerControllerTest.java
  src/test/java/com/dia/dia_be/repository/CustomerRepositoryTest.java
Labels: ✍️TEST, 🌟Development

#59 Feature/get/pb/profile
  src/main/java/com/dia/dia_be/controller/pb/ProfileController.java
  src/main/java/com/dia/dia_be/domain/Pb.java
  src/main/java/com/dia/dia_be/dto/pb/hashtagDTO/RequestHashtagDTO.java
  src/main/java/com/dia/dia_be/dto/pb/hashtagDTO/ResponseHashtagDTO.java
  src/main/java/com/dia/dia_be/dto/pb/profileDTO/RequestProfileDTO.java
  src/main/java/com/dia/dia_be/dto/pb/profileDTO/ResponseProfileDTO.java
  src/main/java/com/dia/dia_be/service/pb/impl/ProfileServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/ProfileServiceIntf.java
  src/test/java/com/dia/dia_be/controller/pb/CustomerControllerTest.java
  src/test/java/com/dia/dia_be/controller/pb/ProfileControllerTest.java
Labels: ✍️TEST, 🌟Development

#60 Feature/pb/journals
  src/main/java/com/dia/dia_be/controller/pb/JournalController.java
  src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
  src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/ReserveService.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
  src/test/java/com/dia/dia_be/controller/pb/JournalControllerTest.java
  src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java
  src/test/java/com/dia/dia_be/controller/vip/VipReserveControllerTest.java
Labels: 🌟Development

#58 [feat] : pb/notifications에 대한 controller, service, test, dto 추가
  src/main/java/com/dia/dia_be/controller/pb/NotificationController.java
  src/main/java/com/dia/dia_be/dto/pb/NotificationDTO.java
  src/main/java/com/dia/dia_be/repository/NotificationRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/NotificationServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/NotificationService.java
  src/test/java/com/dia/dia_be/controller/pb/NotificationControllerTest.java
Labels: ✍️TEST, 🌟Development

#61 Feature/put/pb/reserves
  src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
  src/main/java/com/dia/dia_be/domain/Consulting.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbReserveService.java
  src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java
  src/test/java/com/dia/dia_be/controller/vip/PbReserveControllerTest.java
Labels: ✍️TEST, 🌟Development

#68 [refactor] : CustomerDTO를 req와 res로 분리
  src/main/java/com/dia/dia_be/controller/pb/PbCustomerController.java
  src/main/java/com/dia/dia_be/dto/pb/customerDTO/CustomerDTO.java
  src/main/java/com/dia/dia_be/dto/pb/customerDTO/RequestCustomerDTO.java
  src/main/java/com/dia/dia_be/dto/pb/customerDTO/ResponseCustomerDTO.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbCustomerServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbCustomerService.java
  src/test/java/com/dia/dia_be/controller/pb/PbCustomerControllerTest.java
  src/test/java/com/dia/dia_be/repository/CustomerRepositoryTest.java
Labels: 🌟Development

#71 [feat] : VipNotification의 컨트롤러, 서비스, dto, test 등 추가
  src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
  src/main/java/com/dia/dia_be/dto/vip/ResponseNotificationGetDTO.java
  src/main/java/com/dia/dia_be/repository/NotificationRepository.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipNotificationServiceImpl.java
  src/main/java/com/dia/dia_be/service/vip/intf/VipNotificationService.java
  src/test/java/com/dia/dia_be/controller/vip/VipNotificationControllerTest.java
Labels: ✍️TEST, 🌟Development

#80 Feature/get/pb/upcoming reserves
  src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
  src/main/java/com/dia/dia_be/repository/ConsultingRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbReserveService.java
  src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java
  src/test/java/com/dia/dia_be/repository/ConsultingRepositoryTest.java
Labels: ✍️TEST, 🌟Development

#84 [feat] : 특정 날짜 상담일정(캘린더) 조회
  src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
  src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveByDateDTO.java
  src/main/java/com/dia/dia_be/repository/ConsultingRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbReserveService.java
  src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java
  src/test/java/com/dia/dia_be/repository/ConsultingRepositoryTest.java
Labels: 🌟Development

#83 [refactor] : pbNotificationDTO를 req와 res로 분리
  src/main/java/com/dia/dia_be/controller/pb/PbNotificationController.java
  src/main/java/com/dia/dia_be/dto/pb/NotificationDTO.java
  src/main/java/com/dia/dia_be/dto/pb/notificationDTO/RequestNotificationDTO.java
  src/main/java/com/dia/dia_be/dto/pb/notificationDTO/ResponseNotificationDTO.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbNotificationServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbNotificationService.java
  src/test/java/com/dia/dia_be/controller/pb/PbNotificationControllerTest.java
Labels: 🌟Development

#88 Feature/vip/reserve
  src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
  src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java
  src/main/java/com/dia/dia_be/dto/vip/reserveDTO/ResponseReserveDTO.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipJournalServiceImpl.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
  src/main/java/com/dia/dia_be/service/vip/intf/VipReserveService.java
  src/test/java/com/dia/dia_be/controller/vip/VipNotificationControllerTest.java
  src/test/java/com/dia/dia_be/controller/vip/VipReserveControllerTest.java
Labels: ✍️TEST, 🌟Development

#96 [fix] : 들어온 상담 요청 조회 결과에 customerName 데이터 없는 오류 해결
  src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveDTO.java
Labels: ✍️TEST, 🐞BUG

#99 [feat] : /pb/journals/products?tag= api구현
  src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
  src/main/java/com/dia/dia_be/dto/pb/HashtagDTO/ResponseHashtagDTO.java
  src/main/java/com/dia/dia_be/dto/pb/hashtagDTO/ResponseHashtagDTO.java
  src/main/java/com/dia/dia_be/dto/pb/productDTO/ResponseProductDTO.java
  src/main/java/com/dia/dia_be/dto/pb/profileDTO/ResponseEditProfileDTO.java
  src/main/java/com/dia/dia_be/dto/pb/profileDTO/ResponseProfileDTO.java
  src/main/java/com/dia/dia_be/repository/ProductRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbProductServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbProductService.java
  src/test/java/com/dia/dia_be/controller/pb/PbJournalControllerTest.java
  src/test/java/com/dia/dia_be/repository/ProductRepositoryTest.java
Labels: 🌟Development

#110 [feat] : get/pb/keywords api 개발
  src/main/java/com/dia/dia_be/controller/pb/PbKeywordController.java
  src/main/java/com/dia/dia_be/dto/pb/keywordDTO/ResponseKeywordDTO.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbKeywordServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbKeywordService.java
  src/test/java/com/dia/dia_be/controller/pb/PbJournalControllerTest.java
  src/test/java/com/dia/dia_be/controller/pb/PbKeywordControllerTest.java
  src/test/java/com/dia/dia_be/repository/KeywordRepositoryTest.java
Labels: 🌟Development

#106 [fix] : PbProfileDTO 충돌 문제 해결
  src/main/java/com/dia/dia_be/dto/vip/pbProfileDTO/ResponsePbProfileDTO.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipPbServiceImpl.java
  src/main/java/com/dia/dia_be/service/vip/intf/VipPbService.java
Labels: 🐞BUG

#103 [fix] : customerController에서 손님 목록 조회가 pbId에 따라 검색되게끔 수정
  src/main/java/com/dia/dia_be/controller/pb/PbCustomerController.java
  src/main/java/com/dia/dia_be/repository/CustomerRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbCustomerServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbCustomerService.java
  src/test/java/com/dia/dia_be/controller/pb/PbCustomerControllerTest.java
Labels: 🌟Development, 🐞BUG

#118 Feature/get/vip/journals/scripts
  src/main/java/com/dia/dia_be/dto/vip/journalDTO/ResponseJournalScriptDTO.java
Labels: 🐞BUG

#120 [fix] : 손님 정보 불러올때, 이메일과 패스워드는 응답받지 않음
  src/main/java/com/dia/dia_be/dto/pb/customerDTO/ResponseCustomerDTO.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbCustomerServiceImpl.java
  src/test/java/com/dia/dia_be/controller/pb/PbCustomerControllerTest.java
  src/test/java/com/dia/dia_be/repository/CustomerRepositoryTest.java
Labels: 🐞BUG

#124 [style] : DB 이미지 url을 이미지 서버와 연동
  src/main/resources/data.sql
Labels: 🌟Development

#125 Feature/pb/journals/complete/false
  src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseTemporarySavedJournalDTO.java
  src/main/java/com/dia/dia_be/repository/JournalRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbJournalServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbJournalService.java
  src/test/java/com/dia/dia_be/controller/pb/PbJournalControllerTest.java
  src/test/java/com/dia/dia_be/repository/JournalRepositoryTest.java
Labels: 🌟Development

#127 [fix] : 상담 일정 리스트 오늘 상담도 추가
  src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
Labels: 🐞BUG

#130 [fix] : 알림 컨트롤러 url 수정
  src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
  src/test/java/com/dia/dia_be/controller/vip/VipNotificationControllerTest.java
Labels: 🐞BUG

#137 [fix] : upcomingReserves hopeDate, hopeTime이 현재시점에서 가까운 순으로 정렬
  src/main/java/com/dia/dia_be/controller/pb/PbLoginController.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
Labels: 🐞BUG

#146 [fix] : dto/pb/journalDTO/ResponseJournalDTO를 수정
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseJournalDTO.java
Labels: 🐞BUG

#150 [fix] : getReserve 호출시 customerid도 가져오게끔 controller, dto 수정
  src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
  src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveDTO.java
  src/main/java/com/dia/dia_be/repository/ConsultingRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbReserveService.java
Labels: 🐞BUG

#154 [fix] : 불필요한 요소 청소
  src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
  src/main/java/com/dia/dia_be/repository/ConsultingRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbReserveService.java
Labels: 🐞BUG

#158 [refactor] : Category, Journal, Login return 타입 지정
  src/main/java/com/dia/dia_be/controller/vip/VipCategoryController.java
  src/main/java/com/dia/dia_be/controller/vip/VipJournalController.java
  src/main/java/com/dia/dia_be/controller/vip/VipLoginController.java
Labels: 🌟Development

#165 [fix] : dto content 필드 추가
  src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveDTO.java
Labels: 🌟Development, 🐞BUG

#167 [fix] : ResponseJournalDTO 필드 수정
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseJournalDTO.java
  src/main/java/com/dia/dia_be/dto/pb/productDTO/ResponseProductDTO.java
Labels: 🌟Development

#173 [fix] : ResponseJournalDTO 내 customerId 추가, ResponseProductDTO 내 prod…
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseJournalDTO.java
  src/main/java/com/dia/dia_be/dto/pb/productDTO/ResponseProductDTO.java
Labels: 🌟Development, 🐞BUG

#177 Feature/pb/journals
  src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/ScriptListRequestDTO.java
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/ScriptRequestDTO.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbJournalServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbJournalService.java
Labels: 🌟Development, 🐞BUG

#180 [fix] : 상담 내역에서 오늘의 상담도 보이도록 추가
  src/main/java/com/dia/dia_be/service/vip/impl/VipJournalServiceImpl.java
Labels: 🌟Development

#185 [fix] : pb ResponseReserveDTO 내 시간 표기 형식 변경
  src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveByDateDTO.java
  src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveDTO.java
Labels: 🌟Development, 🐞BUG

#186 [test] : ResponseReserveDTO 내 시간 형식 변경으로 인한 테스트 코드 수정
  src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java
Labels: 🌟Development, 🐞BUG

#195 [fix] : approveReserves 반환 body string -> status code
  src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
Labels: 🐞BUG

#197 Fix/vip/reserves
  src/main/java/com/dia/dia_be/exception/VipErrorCode.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
Labels: 🌟Development

#199 [fix] : 상담 일지가 작성되면 상담 일정에서 제외되도록 수정
  src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
Labels: 🌟Development

#205 [feat] : 로그인 관련 컨트롤러 및 테스트코드 수정
  src/main/java/com/dia/dia_be/controller/vip/VipJournalController.java
  src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
  src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipJournalServiceImpl.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
  src/main/java/com/dia/dia_be/service/vip/intf/VipJournalService.java
  src/main/java/com/dia/dia_be/service/vip/intf/VipReserveService.java
  src/test/java/com/dia/dia_be/controller/vip/VipJournalControllerTest.java
  src/test/java/com/dia/dia_be/controller/vip/VipNotificationControllerTest.java
  src/test/java/com/dia/dia_be/controller/vip/VipReserveControllerTest.java
Labels: 🌟Development

#219 [feat] : 스크립트 삭제 DELETE API 개발
  src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
  src/main/java/com/dia/dia_be/repository/JournalRepository.java
  src/main/java/com/dia/dia_be/service/pb/impl/PbJournalServiceImpl.java
  src/main/java/com/dia/dia_be/service/pb/intf/PbJournalService.java
Labels: 🌟Development

#223 [fix] : product, issue 레포의 sql 소문자로 변경
  src/main/java/com/dia/dia_be/WebDriverConfig.java
  src/main/java/com/dia/dia_be/repository/IssueRepository.java
  src/main/java/com/dia/dia_be/repository/ProductRepository.java
Labels: 🐞BUG

#225 [fix] : WebDriverConfig 주석 제거
  src/main/java/com/dia/dia_be/WebDriverConfig.java
Labels: 🐞BUG

#232 Refactor/swagger UI
  src/main/java/com/dia/dia_be/controller/pb/PbCustomerController.java
  src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
  src/main/java/com/dia/dia_be/controller/pb/PbKeywordController.java
  src/main/java/com/dia/dia_be/controller/pb/PbLoginController.java
  src/main/java/com/dia/dia_be/controller/pb/PbLogoutController.java
  src/main/java/com/dia/dia_be/controller/pb/PbNotificationController.java
  src/main/java/com/dia/dia_be/controller/pb/PbProfileController.java
  src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
  src/main/java/com/dia/dia_be/controller/vip/VipCategoryController.java
  src/main/java/com/dia/dia_be/controller/vip/VipJournalController.java
  src/main/java/com/dia/dia_be/controller/vip/VipLoginController.java
  src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
  src/main/java/com/dia/dia_be/controller/vip/VipPbController.java
  src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java
  src/main/java/com/dia/dia_be/dto/pb/availabilityDTO/RequestAvailabilityDTO.java
  src/main/java/com/dia/dia_be/dto/pb/customerDTO/RequestCustomerDTO.java
  src/main/java/com/dia/dia_be/dto/pb/hashtagDTO/RequestHashtagDTO.java
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/RequestJournalDTO.java
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/ScriptRequestDTO.java
  src/main/java/com/dia/dia_be/dto/pb/loginDTO/LoginForm.java
  src/main/java/com/dia/dia_be/dto/pb/notificationDTO/RequestNotificationDTO.java
  src/main/java/com/dia/dia_be/dto/pb/profileDTO/RequestProfileDTO.java
  src/main/java/com/dia/dia_be/dto/vip/categoryDTO/ResponseCategoryDTO.java
  src/main/java/com/dia/dia_be/dto/vip/loginDTO/RequestVipSignUpDTO.java
  src/main/java/com/dia/dia_be/dto/vip/loginDTO/VipLoginForm.java
  src/main/java/com/dia/dia_be/dto/vip/reserveDTO/RequestReserveDTO.java
  src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
Labels: 📜Docs

#228 [feat] : ResponseJournalDTO에 complete 추가
  src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseJournalDTO.java
Labels: 🌟Development
